---
version: "3.8"
services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - /portainer/files/heimdall/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    runtime: nvidia

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /portainer/files/jellyfin/config:/config
      - /portainer/files/jellyfin/cache:/cache
      - /mnt/ssd1/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - /portainer/files/qbittorrent/config:/config
      - /portainer/files/downloads:/downloads
      - /mnt/ssd1/media:/media
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /portainer/files/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /portainer/files/sonarr/config:/config
      - /mnt/ssd1/media/tvshows:/tv
      - /mnt/ssd1/media/anime:/anime
      - /portainer/files/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /portainer/files/radarr/config:/config
      - /mnt/ssd1/media/movies:/movies
      - /portainer/files/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    volumes:
      - /portainer/files/jellyseerr/config:/app/config
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /portainer/files/lidarr/config:/config
      - /mnt/ssd1/media/music:/music
      - /portainer/files/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped