services:
  heimdall:
      image: linuxserver/heimdall
      container_name: heimdall
      volumes:
        - /docker/appdata/heimdall/:/config
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Asia/Kolkata
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    devices:
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    volumes:
      - /docker/appdata/jellyfin/config:/config
      - /docker/appdata/jellyfin/cache:/cache
      - /data/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/jellyseerr:/app/config
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - /docker/appdata/qbittorrent/config:/config
      - /docker/appdata/downloads:/downloads
      - /data/torrents/:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /docker/appdata/radarr:/config
      - /data:/data
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /docker/appdata/sonarr:/config
      - /data:/data
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - 9696:9696
    volumes:
      - /docker/appdata/prowlarr:/config
      - /data:/data
